# Generated by Django 4.2.6 on 2023-11-30 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discussion", "0002_alter_post_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="post_id",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="post",
            new_name="post_id",
        ),
    ]
