# Generated by Django 4.2.6 on 2023-12-09 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discussion", "0005_post_likes_alter_like_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
