# Generated by Django 4.2.6 on 2023-11-29 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=200,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_email",
                        message="Enter a valid email address.",
                        regex="^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_password",
                        message="Password must be at least 8 characters long and include at least one letter, one digit, and one special character.",
                        regex="^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$",
                    )
                ],
            ),
        ),
    ]
