# Generated by Django 4.2.6 on 2023-11-29 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_email_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_password",
                        message="Password must be at least 8 characters long and include at least one letter, one digit, and one special character.",
                        regex="^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#())?&]{8,}$",
                    )
                ],
            ),
        ),
    ]
