# Generated by Django 4.2.6 on 2023-12-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="course_studied",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="tel_code_kin",
            field=models.CharField(default="+233", max_length=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="current_organization",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
