# Generated by Django 4.2.6 on 2023-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="momo_number",
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
