# Generated by Django 4.2.6 on 2023-12-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_payment_momo_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="momo_number",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
