# Generated by Django 4.2.6 on 2023-12-15 04:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_alter_payment_momo_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Intiatives",
            new_name="Initiatives",
        ),
        migrations.RenameField(
            model_name="initiatives",
            old_name="intiative_id",
            new_name="initiative_id",
        ),
    ]
